#local config if config server connection lost
spring:
  application:
    name: 'bbp-users-service'
  mvc:
    favicon:
      enabled: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
  datasource:
    url: 'jdbc:postgresql://localhost:5430/users'
    username: 'usersuser'
    password: 'docker'

    driver-class-name: 'org.postgresql.Driver'
server:
  port: 8030
eureka:
  client:
    registryFetchIntervalInSeconds: 10
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

kafka:
  bootstrapAddress: localhost:9092
  topics:
    email: template_email_sender